// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proje05_MVC_EfCore_CodeFirst_Tekrar.Models;

#nullable disable

namespace Proje05_MVC_EfCore_CodeFirst_Tekrar.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20221117102100_InitialDatabase")]
    partial class InitialDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.11");

            modelBuilder.Entity("Proje05_MVC_EfCore_CodeFirst_Tekrar.Models.Bolum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Bolums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Matematik"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Türkçe"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fizik"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kimya"
                        });
                });

            modelBuilder.Entity("Proje05_MVC_EfCore_CodeFirst_Tekrar.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Yas")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mert",
                            Yas = 23
                        },
                        new
                        {
                            Id = 2,
                            Name = "Osman",
                            Yas = 17
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mehmet",
                            Yas = 21
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kerem",
                            Yas = 22
                        });
                });

            modelBuilder.Entity("Proje05_MVC_EfCore_CodeFirst_Tekrar.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BolumId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Yas")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BolumId");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BolumId = 4,
                            Name = "Selami",
                            Yas = 45
                        },
                        new
                        {
                            Id = 2,
                            BolumId = 3,
                            Name = "Yasin",
                            Yas = 54
                        },
                        new
                        {
                            Id = 3,
                            BolumId = 1,
                            Name = "Doğan",
                            Yas = 28
                        },
                        new
                        {
                            Id = 4,
                            BolumId = 2,
                            Name = "Mahmut",
                            Yas = 37
                        },
                        new
                        {
                            Id = 5,
                            BolumId = 1,
                            Name = "Aysel",
                            Yas = 33
                        });
                });

            modelBuilder.Entity("Proje05_MVC_EfCore_CodeFirst_Tekrar.Models.Teacher", b =>
                {
                    b.HasOne("Proje05_MVC_EfCore_CodeFirst_Tekrar.Models.Bolum", "Bolum")
                        .WithMany()
                        .HasForeignKey("BolumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bolum");
                });
#pragma warning restore 612, 618
        }
    }
}
